# -*- coding: utf-8 -*-
"""python_section_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGPY6bnmfus1bP6WFXWm41GJNBu7W2B-

Question 10: Unroll Distance Matrix
"""

import pandas as pd

def unroll_distance_matrix(distance_matrix):
    # Create a list to store the rows for the new DataFrame
    data = []

    # Iterate over the rows and columns of the distance matrix
    for id_start in distance_matrix.index:
        for id_end in distance_matrix.columns:
            # Exclude diagonal (where id_start == id_end)
            if id_start != id_end:
                distance = distance_matrix.at[id_start, id_end]
                data.append({'id_start': id_start, 'id_end': id_end, 'distance': distance})

    # Convert the list of dictionaries into a DataFrame
    unrolled_df = pd.DataFrame(data)

    return unrolled_df

# Example Usage
# Assuming distance_matrix is the DataFrame generated from Question 9
# unrolled_matrix = unroll_distance_matrix(distance_matrix)
# print(unrolled_matrix)

"""Question 12: Calculate Toll Rate"""

import pandas as pd

def calculate_toll_rate(unrolled_df):
    # Define rate coefficients for each vehicle type
    rate_coefficients = {
        'moto': 0.8,
        'car': 1.2,
        'rv': 1.5,
        'bus': 2.2,
        'truck': 3.6
    }

    # Add columns for each vehicle type and calculate the toll rate
    unrolled_df['moto'] = unrolled_df['distance'] * rate_coefficients['moto']
    unrolled_df['car'] = unrolled_df['distance'] * rate_coefficients['car']
    unrolled_df['rv'] = unrolled_df['distance'] * rate_coefficients['rv']
    unrolled_df['bus'] = unrolled_df['distance'] * rate_coefficients['bus']
    unrolled_df['truck'] = unrolled_df['distance'] * rate_coefficients['truck']

    return unrolled_df

# Example Usage
# Assuming unrolled_df is the DataFrame created in Question 10
# toll_rates_df = calculate_toll_rate(unrolled_df)
# print(toll_rates_df)